package creditcardfrauddictection;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author damhiesax
 */
public class OneCard extends javax.swing.JFrame {
   Date d;
   DefaultTableModel dataSet;
   int j;
    DbConnect db = new DbConnect();
    Variables var= new Variables();
    String query; 
     /**
     * Creates new form LogHistory
     */
    public OneCard() {
        initComponents();
       fetch("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton5.setText("Block Card");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(540, 410, 90, 30);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable( int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 50, 600, 340);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("My Cards");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 10, 210, 40);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 410, 140, 30);

        jLabel1.setText("net Balance");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(34, 410, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-686)/2, (screenSize.height-496)/2, 686, 496);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
        if(jTable1.getSelectedRow()<0){
        JOptionPane.showMessageDialog(rootPane, "Please select the card you wish to block");
        return;
        }
           new SecurityQues(new javax.swing.JFrame(), true).setVisible(true);
        
        String card_id= jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        try {
            db.ps=db.con.prepareStatement("update attacc set status='1' where no='"+card_id+"'")  ; 
          db.ps.execute(); 
          JOptionPane.showMessageDialog(rootPane, "The Card with "+card_id+" is now blocked");
      new TransactionHistory(card_id,"cash transfer", "withdraw",0);
 
        } catch (Exception e) {
            e.printStackTrace();
        } 
        
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
void fetch(String query){
    double amt=0;
    j=0;
     dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("Name");
        dataSet.addColumn("Card No");
        dataSet.addColumn("Balance");
        dataSet.addColumn("Status");
  try {
      query="select name,no,amt,atmacc.status from atmacc,bank_account where no='"+var.getCard_id()+"' and atmacc.bank=bank_account.bank_name and usr_id='"+var.getId()+"'";
         db.rs = db.st.executeQuery(query);
           while (db.rs.next()) { 
               Object[] data = new Object[]{++j,db.rs.getString("name"),db.rs.getString("no"),db.rs.getString(3),db.rs.getString(4)};
                dataSet.addRow(data);
               amt+= db.rs.getInt(3);
            }
           jTable1.setModel(dataSet);
          jTextField1.setText("#"+amt);
        } catch (Exception e) {
     JOptionPane.showMessageDialog(rootPane, "An Error occur while fecthing information!!!");
    }
          
}
  
}
