/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creditcardfrauddictection;

import javax.swing.JOptionPane;

/**
 *
 * @author tosyngy
 */
public class Recharge extends javax.swing.JFrame {

    DbConnect db = new DbConnect();
    double amt;
    Variables var = new Variables();

    /**
     * Creates new form Welcome
     */
    public Recharge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(null);

        jButton3.setText("1. My mobile No");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(60, 30, 290, 41);

        jButton4.setText("2. Other");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(60, 80, 290, 41);

        jButton8.setText("cancel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(290, 140, 80, 30);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mobile Recharge"));
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 10, 380, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-225)/2, 416, 225);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        double rec = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Amount to Recharge"));
        int id = 0;
        String mobile = "";
         new SecurityQues(new javax.swing.JFrame(), true).setVisible(true);
        try {
            db.rs = db.st.executeQuery("Select amt,bank_account.id,register_detaila.`mobile no` from atmacc,bank_account,register_detaila where no='" + var.getCard_id() + "' and atmacc.bank=bank_account.bank_name and bank_account.usr_id='"+var.getId()+"'  and register_detaila.id='"+var.getId()+"'");
            if (db.rs.next()) {
                amt = db.rs.getDouble(1);
                id = db.rs.getInt(2);
                mobile = db.rs.getString(3);
                recharge(amt, rec, mobile, id);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
       String mobile= JOptionPane.showInputDialog(rootPane, "Enter the Phone No.");
        double rec = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Amount to Recharge"));
         new SecurityQues(new javax.swing.JFrame(), true).setVisible(true);
        int id = 0;
        try {
            db.rs = db.st.executeQuery("Select amt,bank_account.id from atmacc,bank_account where no='" + var.getCard_id() + "' and atmacc.bank=bank_account.bank_name  and usr_id='"+var.getId()+"'");
            if (db.rs.next()) {
                amt = db.rs.getDouble(1);
                id = db.rs.getInt(2);
            }
            recharge(amt, rec, mobile, id);
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close app");
        if (a == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recharge().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    void recharge(double amt, double rec, String mobile, int id) {
        try {
            if (amt > rec) {
                amt -= rec;
                db.ps = db.con.prepareStatement("update bank_account set amt='" + amt + "' where id='" + id + "'");
                db.ps.execute();
                JOptionPane.showMessageDialog(rootPane, "Mobile no " + mobile + " Recharged Successfully");
                new TransactionHistory(var.getCard_id(), "mobile recharge", "withdraw", rec);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Insufficient Foud. Your Acc Statement is: #" + amt);
            }
        } catch (Exception e) {
        }
    }
}
