package creditcardfrauddictection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author damhiesax
 */
public class Transfer extends javax.swing.JFrame {

    DbConnect db = new DbConnect();
    ResultSetMetaData md;
    String firstname, lastname, PassWord, address, mobileNo, administrator, username, Userid;
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    Statement st;
    Variables var;
    static int type;
    double amt;

    /**
     * Creates new form UserReg
     */
    public Transfer(String amt, String acc, String text, int t) {
        initComponents();
        setTitle("Cash Transfer");
        type = t;
        var = new Variables();
        if (type == 0) {
        } else {
            jTextField3.setText(amt);
            jTextField3.setEditable(false);
            jTextField4.setText(acc);
            jTextField4.setEditable(false);
            jTextArea1.setText(text);
            jLabel2.setVisible(false);
            jComboBox1.setVisible(false);
            jComboBox1.setSelectedIndex(1);
            if (type == 1 && amt.isEmpty()) {
                jTextField3.setEditable(true);
                jTextField4.setEditable(true);
                jTextArea1.setEditable(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Registraion");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("Bill Message");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 210, 80, 14);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 340, 100, 27);

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 340, 100, 27);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Transfer");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 0, 80, 30);

        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 0, 350, 30);

        jLabel5.setText("Amount:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 70, 80, 14);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 60, 220, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Bank Name --", "GTB", "access", "UBA", "FirstBank", "FCMB", "Diamond", "Wema" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(120, 160, 220, 30);

        jLabel6.setText("Account No:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 120, 80, 14);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(120, 110, 220, 30);

        jLabel2.setText("Bank Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 170, 80, 14);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 210, 220, 120);

        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 40, 350, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-389)/2, (screenSize.height-411)/2, 389, 411);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addnew();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
         Object ch = evt.getKeyChar();
        num(jTextField3, ch);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

     public void num(JTextField a, Object ch) {
        String cha = ch.toString();
        if (!"123456789.0\b\n".contains(cha)) {
            a.setText(a.getText().substring(0, (a.getText().length() - 1)));
        }
    }

    public void textSize(JTextField a, int i) {
        if (a.getText().length() > i) {
            a.setText(a.getText().substring(0, i));
        }
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer("", "", "", 0).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    void addnew() {
        String emt = "";
        int user_id = 0;
        double user_amt = 0;
        if (jTextField3.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Please Specify the amount you wish to transfer");
            return;
        }
        if (jTextField4.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Account No Require");
            return;
        }
        if (jComboBox1.getSelectedIndex() == 0 && type == 1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a bank");
            return;
        }


        int id = 0;
        try {
            db.rs = db.st.executeQuery("Select amt,bank_account.id from atmacc,bank_account where no='" + var.getCard_id() + "' and atmacc.bank=bank_account.bank_name and usr_id='"+var.getId()+"'");
            if (db.rs.next()) {
                amt = db.rs.getDouble(1);
                id = db.rs.getInt(2);
            }
            if (type == 0) {
                db.rs = db.st.executeQuery("Select amt,bank_account.id,name from atmacc,bank_account where no='" + jTextField4.getText() + "' and bank_account.bank_name='" + jComboBox1.getSelectedItem().toString() + "' and atmacc.bank=bank_account.bank_name");
                if (db.rs.next()) {
                    user_amt = db.rs.getDouble(1);
                    user_id = db.rs.getInt(2);
                    JOptionPane.showMessageDialog(rootPane, "Please Verify the Information\nYou are transferring the sum of \n#" + jTextField3.getText() + " to " + db.rs.getString("name") + " \nwith account no. " + jTextField4.getText());
                    int chk = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to continue?");
                    if (chk == JOptionPane.NO_OPTION) {
                        return;
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Account No. does not exit");
                    return;
                }
            }
            new SecurityQues(new javax.swing.JFrame(), true).setVisible(true);

            if (amt > Double.parseDouble(jTextField3.getText())) {
                amt -= Double.parseDouble(jTextField3.getText());
                db.ps = db.con.prepareStatement("update bank_account set amt='" + amt + "' where id='" + id + "'");
                db.ps.execute();
                if (type == 1) {
                    user_amt += Double.parseDouble(jTextField3.getText());
                    db.ps = db.con.prepareStatement("update bank_account set amt='" + user_amt + "' where id='" + user_id + "'");
                    db.ps.execute();
                }
                JOptionPane.showMessageDialog(rootPane, "Transaction Successfully");
                if (type == 1) {
                    new TransactionHistory(var.getCard_id(), "bill payment", "withdraw", Double.parseDouble(jTextField3.getText()));

                } else {
                    new TransactionHistory(var.getCard_id(), "cash transfer", "withdraw", Double.parseDouble(jTextField3.getText()));
                }
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Insufficient Foud. Your Acc Statement is: #" + amt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
